/**
 * Wiki Writer — writes generated wiki pages to a GitHub repo's wiki.
 * GitHub Wiki is a separate git repo at https://github.com/{owner}/{repo}.wiki.git
 * Must be accessed via git clone/push, not the contents API.
 */

import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import os from 'os';

/**
 * Check if wiki is enabled on the repo.
 * @returns {Promise<boolean>}
 */
export async function initializeWiki(octokit, owner, repo) {
  const { data: repoData } = await octokit.request('GET /repos/{owner}/{repo}', { owner, repo });
  if (!repoData.has_wiki) {
    console.warn(`Wiki is not enabled on ${owner}/${repo}`);
    return false;
  }
  return true;
}

/**
 * Get an authenticated clone URL for the wiki repo.
 */
async function getWikiCloneUrl(octokit, owner, repo) {
  const { data: { token } } = await octokit.request('POST /app/installations/{installation_id}/access_tokens', {
    installation_id: (await octokit.auth()).installationId,
  }).catch(() => ({ data: { token: null } }));

  // Use the octokit auth to get a token
  const auth = await octokit.auth({ type: 'installation' });
  return `https://x-access-token:${auth.token}@github.com/${owner}/${repo}.wiki.git`;
}

/**
 * Clone the wiki repo, write pages, commit and push.
 * @returns {Promise<string[]>} Array of page URLs
 */
export async function writeAllPages(octokit, owner, repo, pages) {
  const auth = await octokit.auth({ type: 'installation' });
  const cloneUrl = `https://x-access-token:${auth.token}@github.com/${owner}/${repo}.wiki.git`;
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'sage-wiki-'));

  try {
    // Clone the wiki repo
    console.log(`  Cloning wiki repo...`);
    execSync(`git clone "${cloneUrl}" "${tmpDir}/wiki"`, {
      stdio: 'pipe',
      timeout: 30000,
    });

    const wikiDir = path.join(tmpDir, 'wiki');

    // Configure git
    execSync('git config user.email "sage[bot]@users.noreply.github.com"', { cwd: wikiDir, stdio: 'pipe' });
    execSync('git config user.name "Sage"', { cwd: wikiDir, stdio: 'pipe' });

    // Write each page
    const urls = [];
    for (const page of pages) {
      if (page.title.toLowerCase() === 'home') continue;
      const filename = titleToFilename(page.title) + '.md';
      fs.writeFileSync(path.join(wikiDir, filename), page.content);
      urls.push(`https://github.com/${owner}/${repo}/wiki/${titleToFilename(page.title)}`);
      console.log(`  Written: ${page.title}`);
    }

    // Build Home page as table of contents
    const tocLines = ['# Wiki', '', `> Generated by Sage for \`${owner}/${repo}\``, ''];

    const categories = {};
    for (const page of pages) {
      if (page.title.toLowerCase() === 'home') continue;
      const cat = page.category || 'general';
      if (!categories[cat]) categories[cat] = [];
      categories[cat].push(page);
    }

    for (const [category, catPages] of Object.entries(categories)) {
      tocLines.push(`## ${category.charAt(0).toUpperCase() + category.slice(1)}`);
      tocLines.push('');
      for (const p of catPages) {
        tocLines.push(`- [${p.title}](${titleToFilename(p.title)})`);
      }
      tocLines.push('');
    }

    fs.writeFileSync(path.join(wikiDir, 'Home.md'), tocLines.join('\n'));
    urls.unshift(`https://github.com/${owner}/${repo}/wiki/Home`);
    console.log('  Written: Home (table of contents)');

    // Stage, commit, push
    execSync('git add -A', { cwd: wikiDir, stdio: 'pipe' });

    try {
      execSync('git commit -m "Update wiki via Sage"', { cwd: wikiDir, stdio: 'pipe' });
      execSync('git push', { cwd: wikiDir, stdio: 'pipe', timeout: 30000 });
      console.log('  Pushed to wiki repo');
    } catch (commitErr) {
      // If nothing changed, git commit will fail — that's ok
      if (commitErr.message?.includes('nothing to commit')) {
        console.log('  No changes to push');
      } else {
        throw commitErr;
      }
    }

    return urls;
  } finally {
    // Clean up temp directory
    fs.rmSync(tmpDir, { recursive: true, force: true });
  }
}

/**
 * Write a single wiki page (for incremental updates).
 * @returns {Promise<string>} URL of the wiki page
 */
export async function writePage(octokit, owner, repo, title, content) {
  const auth = await octokit.auth({ type: 'installation' });
  const cloneUrl = `https://x-access-token:${auth.token}@github.com/${owner}/${repo}.wiki.git`;
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'sage-wiki-'));

  try {
    execSync(`git clone "${cloneUrl}" "${tmpDir}/wiki"`, { stdio: 'pipe', timeout: 30000 });

    const wikiDir = path.join(tmpDir, 'wiki');
    execSync('git config user.email "sage[bot]@users.noreply.github.com"', { cwd: wikiDir, stdio: 'pipe' });
    execSync('git config user.name "Sage"', { cwd: wikiDir, stdio: 'pipe' });

    const filename = titleToFilename(title) + '.md';
    fs.writeFileSync(path.join(wikiDir, filename), content);

    execSync('git add -A', { cwd: wikiDir, stdio: 'pipe' });

    try {
      execSync(`git commit -m "Update ${title} via Sage"`, { cwd: wikiDir, stdio: 'pipe' });
      execSync('git push', { cwd: wikiDir, stdio: 'pipe', timeout: 30000 });
    } catch (commitErr) {
      if (!commitErr.message?.includes('nothing to commit')) throw commitErr;
    }

    return `https://github.com/${owner}/${repo}/wiki/${titleToFilename(title)}`;
  } finally {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  }
}

/**
 * Get all existing wiki pages.
 * @returns {Promise<Array<{title: string, filename: string, content: string}>>}
 */
export async function getExistingPages(octokit, owner, repo) {
  const auth = await octokit.auth({ type: 'installation' });
  const cloneUrl = `https://x-access-token:${auth.token}@github.com/${owner}/${repo}.wiki.git`;
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'sage-wiki-'));

  try {
    execSync(`git clone "${cloneUrl}" "${tmpDir}/wiki"`, { stdio: 'pipe', timeout: 30000 });

    const wikiDir = path.join(tmpDir, 'wiki');
    const files = fs.readdirSync(wikiDir).filter(f => f.endsWith('.md'));

    return files.map(f => ({
      title: filenameToTitle(f),
      filename: f,
      content: fs.readFileSync(path.join(wikiDir, f), 'utf-8'),
    }));
  } catch {
    return [];
  } finally {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function titleToFilename(title) {
  return title.replace(/\s+/g, '-');
}

function filenameToTitle(filename) {
  return filename.replace(/\.md$/, '').replace(/-/g, ' ');
}
